### PR TITLE
Added .let() function and destructuring declaration examples

### PR DESCRIPTION
**Pull request by alexeybrod**

### CODE REVIEW

**Comment by hhariri** [comment]
Thanks. Adding to index.

**Comment by hhariri** [comment]
I've fixed a bunch of compiler errors on this one. If you could, please make sure examples are complete and compile beforehand. Thanks.

**Comment by alexeybrod** [comment]
Sure, will make them more complete next time. What about second example of let() function? Should I make it compile and add again?

**Comment by hhariri** [comment]
That would be great thanks.

**Pull request merged**
